### ISSUE TITLE
Installing on Mac OS X

### ISSUE THREAD

**Issue by jomo666** [mamod/JavaScript-Shell#1]
In the Mac OS X (according to http://perldoc.perl.org/perlport.html) the $^O variable contains "darwin". The following allows clean install on OS X (at least on my system) :).

```
diff --git a/Makefile.PL b/Makefile.PL
index 012a3d2..01bb535 100644
--- a/Makefile.PL
+++ b/Makefile.PL
@@ -37,7 +37,7 @@ sub getShell {
     my $file;
     if ($os =~ /^MS/i){
        $file = 'jsshell-win32.zip';
-    } elsif ($os =~ /^Mac/i){
+    } elsif ($os =~ /^(Mac|darwin)/i){
        $file = 'jsshell-mac.zip';
     } else {
        if ($Config{'archname'} =~ m/x86/){
```

Or, maybe the `Mac` isn't even needed and enough to have `darwin`.

**Comment by mamod** [comment]
Really??
Where the hell `Mac` came from? :))
From the docs I can see that darwin is enough, and no need to use Mac at all, would you like to submit a poll request or prefer me to fix this :)

**Comment by jomo666** [comment]
Of course, I prefer your fix. Thank you. :) :)
